pnpMode: loose

packageExtensions:
  '@google-cloud/common@*':
    dependencies:
      events: '*'
  '@google-cloud/functions-framework@*':
    dependencies:
      '@types/express': '*'
  '@types/express@*':
    dependencies:
      body-parser: '*'
      'serve-static': '*'
      qs: '*'
  '@types/express-serve-static-core@*':
    dependencies:
      events: '*'
      range-parser: '*'
      qs: '*'
  '@types/serve-static@*':
    dependencies:
      mime: '*'
  'cloudevents@*':
    dependencies:
      events: '*'
  'hash-stream-validation@*':
    dependencies:
      fast-crc32c: '*'
  'google-auth-library@*':
    dependencies:
      events: '*'
  'follow-redirects@*':
    dependencies:
      debug: '*'
  'debug@*':
    dependencies:
      supports-color: '*'
  'ws@*':
    dependencies:
      bufferutil: '*'
      utf-8-validate: '*'
  'retry-request@*':
    dependencies:
      request: '*'
